### ISSUE TITLE
Rebase checklist

### ISSUE THREAD

**Issue by colesbury** [colesbury/nogil-3.12-final#1]
Crossed out entries indicate commits that should not be ported, usually because they were fixed between 3.12.0a4 and 3.12.0.

- [x] [`602b61f29c5`](https://github.com/colesbury/nogil-3.12/commit/602b61f29c5) Modify GitHub actions workflows for nogil-3.12 rebase
- [ ] ~~[`fdc1aa9edf4`](https://github.com/colesbury/nogil-3.12/commit/fdc1aa9edf4) gh-101981: Update macOS workflow~~
- [ ] ~~[`0ef500edf76`](https://github.com/colesbury/nogil-3.12/commit/0ef500edf76) gh-101408: use _PyType_PreHeaderSize in more places~~
- [ ] [`e3bd9af5af2`](https://github.com/colesbury/nogil-3.12/commit/e3bd9af5af2) gh-101438: possible fix for ElementTree.iterparse leak
- [x] ~~[`c920d2920fe`](https://github.com/colesbury/nogil-3.12/commit/c920d2920fe) test_generators: fix env changed message~~
- [x] ~~[`93f7a9f9ca1`](https://github.com/colesbury/nogil-3.12/commit/93f7a9f9ca1) test_tarfile: skip test_add_dir_getmember when uid is too large~~
- [x] [`7cc35883211`](https://github.com/colesbury/nogil-3.12/commit/7cc35883211) test_tools: skip test if flaky when run via 'make test'
- [ ] [`cefe5dfee9f`](https://github.com/colesbury/nogil-3.12/commit/cefe5dfee9f) configure: disallow "--with-trace-refs"
- [ ] [`dcddbe2ddb3`](https://github.com/colesbury/nogil-3.12/commit/dcddbe2ddb3) configure: add support for --with-thread-sanitizer
- [ ] [`dbb23adf324`](https://github.com/colesbury/nogil-3.12/commit/dbb23adf324) configure: avoid re-freezing frozen modules
- [x] #2
- [ ] [`385eb1d99c1`](https://github.com/colesbury/nogil-3.12/commit/385eb1d99c1) pyport: add new macros
- [ ] [`de2be447b30`](https://github.com/colesbury/nogil-3.12/commit/de2be447b30) Make PyThreadState_GET thread-local
- [ ] [`17f23253c1f`](https://github.com/colesbury/nogil-3.12/commit/17f23253c1f) Skip subinterpreter tests that run on "incorrect" thread
- [ ] [`a24dc2ecc31`](https://github.com/colesbury/nogil-3.12/commit/a24dc2ecc31) pystate: keep track of attached vs. detached state
- [ ] #3
- [ ] [`6845b133ccd`](https://github.com/colesbury/nogil-3.12/commit/6845b133ccd) critical_section: helpers for fine-grained locking
- [ ] [`7a7aca096bc`](https://github.com/colesbury/nogil-3.12/commit/7a7aca096bc) getargs.c: make parser_init thread-safe
- [ ] [`8ed62cab6ac`](https://github.com/colesbury/nogil-3.12/commit/8ed62cab6ac) pystate: use _PyRawMutex for internal mutexes
- [ ] [`4ab575721bb`](https://github.com/colesbury/nogil-3.12/commit/4ab575721bb) Change "SOABI" and sys.implementation.name and define Py_NOGIL
- [ ] [`f546dbf16a9`](https://github.com/colesbury/nogil-3.12/commit/f546dbf16a9) Enable/disable the GIL at runtime
- [ ] [`e15443b1f23`](https://github.com/colesbury/nogil-3.12/commit/e15443b1f23) ceval: move eval_breaker to per-thread state
- [ ] [`464b96fe93e`](https://github.com/colesbury/nogil-3.12/commit/464b96fe93e) Add _thread.CriticalLock which prevents the current thread from parking
- [ ] [`cfb6ed1e5ac`](https://github.com/colesbury/nogil-3.12/commit/cfb6ed1e5ac) multiprocessing: use CriticalLock in a few places
- [ ] [`b6b12a9a94e`](https://github.com/colesbury/nogil-3.12/commit/b6b12a9a94e) Implement biased reference counting
- [ ] [`7b6b6f1a010`](https://github.com/colesbury/nogil-3.12/commit/7b6b6f1a010) unicode: immortalize interned strings
- [ ] [`fc173e3711e`](https://github.com/colesbury/nogil-3.12/commit/fc173e3711e) unicode: always immortalize interned strings
- [ ] [`dd9b78460c5`](https://github.com/colesbury/nogil-3.12/commit/dd9b78460c5) Add safe memory reclamation scheme based on FreeBSD's GUS
- [ ] [`a595fc15939`](https://github.com/colesbury/nogil-3.12/commit/a595fc15939) Create io.BytesIO() in destructor of test_io.py
- [ ] [`901e1349212`](https://github.com/colesbury/nogil-3.12/commit/901e1349212) Add mimalloc v2.0.9
- [ ] [`941b4d499eb`](https://github.com/colesbury/nogil-3.12/commit/941b4d499eb) mimalloc: minimal changes for use in Python
- [ ] [`d28ad6a8ffb`](https://github.com/colesbury/nogil-3.12/commit/d28ad6a8ffb) mimalloc: workaround mimalloc issue 691
- [ ] [`d447b698085`](https://github.com/colesbury/nogil-3.12/commit/d447b698085) mimalloc: changes to support separate heaps
- [ ] [`ca879028299`](https://github.com/colesbury/nogil-3.12/commit/ca879028299) mimalloc: split thread exiting from abandoning heaps
- [ ] [`9561aeaf5e0`](https://github.com/colesbury/nogil-3.12/commit/9561aeaf5e0) mimalloc: don't fill in first N bytes with debug values
- [ ] [`632b27af708`](https://github.com/colesbury/nogil-3.12/commit/632b27af708) mimalloc: enable a form of MI_ENCODE_FREELIST
- [ ] [`10adbc19d95`](https://github.com/colesbury/nogil-3.12/commit/10adbc19d95) mimalloc: abort when detecting double frees
- [ ] [`a4fa553a1bb`](https://github.com/colesbury/nogil-3.12/commit/a4fa553a1bb) mimalloc: faster block visitor
- [ ] [`367a7b0e559`](https://github.com/colesbury/nogil-3.12/commit/367a7b0e559) mimalloc: tag pages with qsbr counter
- [ ] [`19f93dd84b4`](https://github.com/colesbury/nogil-3.12/commit/19f93dd84b4) mimalloc: use relaxed atomics for block->next
- [ ] [`672e119ba05`](https://github.com/colesbury/nogil-3.12/commit/672e119ba05) obmalloc: use separate mimalloc heaps in obmalloc.c
- [ ] [`d13c63dee99`](https://github.com/colesbury/nogil-3.12/commit/d13c63dee99) pymem: remove uses of _PyMem_SetDefaultAllocator during finalization
- [ ] [`3991a6d3229`](https://github.com/colesbury/nogil-3.12/commit/3991a6d3229) Always include space for managed dict/weakref for now
- [ ] [`40046f41e03`](https://github.com/colesbury/nogil-3.12/commit/40046f41e03) specify offsets in pycore_object.h
- [ ] [`254e4196d6f`](https://github.com/colesbury/nogil-3.12/commit/254e4196d6f) clinic: use _PyGC_Head_UNUSED instead of PyGC_Head
- [ ] [`e8c13ea8f8d`](https://github.com/colesbury/nogil-3.12/commit/e8c13ea8f8d) gc: swap order of PyGC_Head and managed dict/weakref
- [ ] [`654be8ffd6f`](https://github.com/colesbury/nogil-3.12/commit/654be8ffd6f) gc: make the garbage collector non-generational
- [ ] [`967fe314739`](https://github.com/colesbury/nogil-3.12/commit/967fe314739) gc: Traverese mimalloc heaps to find all objects.
- [ ] [`0dddcb6f9d7`](https://github.com/colesbury/nogil-3.12/commit/0dddcb6f9d7) weakref: make weakrefs thread-safe without the GIL
- [ ] [`410ba1036a6`](https://github.com/colesbury/nogil-3.12/commit/410ba1036a6) dtoa: make dtoa thread-safe
- [ ] [`6540bf3e6ad`](https://github.com/colesbury/nogil-3.12/commit/6540bf3e6ad) unicode: make unicodeobject.c thread-safe
- [ ] [`5d006db9fab`](https://github.com/colesbury/nogil-3.12/commit/5d006db9fab) codecs.c: fix race condition
- [ ] [`d1b5ed128e2`](https://github.com/colesbury/nogil-3.12/commit/d1b5ed128e2) _threadmodule: make _thread.lock thread-safe
- [ ] [`cfc11bcb1ae`](https://github.com/colesbury/nogil-3.12/commit/cfc11bcb1ae) typeobject: thread safety
- [ ] [`cfecf6f4eb2`](https://github.com/colesbury/nogil-3.12/commit/cfecf6f4eb2) threading: remove _tstate_lock from threading.Thread
- [ ] [`2864b6b36e1`](https://github.com/colesbury/nogil-3.12/commit/2864b6b36e1) gc: implement stop-the-world GC
- [ ] [`c1befd76897`](https://github.com/colesbury/nogil-3.12/commit/c1befd76897) Stop the world before fork() and Python shutdown
- [ ] [`82800d8ec86`](https://github.com/colesbury/nogil-3.12/commit/82800d8ec86) ceval: stop the world when enabling profiling/tracing for all threads
- [ ] [`7423dff3449`](https://github.com/colesbury/nogil-3.12/commit/7423dff3449) pystate: use stop-the-world in a few places
- [ ] [`86efa7dfe3f`](https://github.com/colesbury/nogil-3.12/commit/86efa7dfe3f) pystate: implement _PyRuntime.multithreaded
- [ ] [`74df7785f57`](https://github.com/colesbury/nogil-3.12/commit/74df7785f57) pyqueue: add internal queue data structure
- [ ] [`4450445f512`](https://github.com/colesbury/nogil-3.12/commit/4450445f512) pymem: add _PyMem_FreeQsbr
- [ ] [`7e60a01aee7`](https://github.com/colesbury/nogil-3.12/commit/7e60a01aee7) queue: make SimpleQueue thread-safe
- [ ] [`da071fadeac`](https://github.com/colesbury/nogil-3.12/commit/da071fadeac) ordereddict: simplify Python implementation
- [ ] [`f7b87a06874`](https://github.com/colesbury/nogil-3.12/commit/f7b87a06874) ordereddict: remove C implementation
- [ ] [`d896dfc8dbc`](https://github.com/colesbury/nogil-3.12/commit/d896dfc8dbc) dict: make dict thread-safe
- [ ] [`df4c51f82bf`](https://github.com/colesbury/nogil-3.12/commit/df4c51f82bf) list: make list thread-safe
- [ ] [`4ca2924f0d1`](https://github.com/colesbury/nogil-3.12/commit/4ca2924f0d1) set: make set thread-safe
- [ ] [`3cfbc49229d`](https://github.com/colesbury/nogil-3.12/commit/3cfbc49229d) moduleobject: fix data races
- [ ] [`5722416ef50`](https://github.com/colesbury/nogil-3.12/commit/5722416ef50) _threadmodule: thread-safety fixes
- [ ] [`31ec6f02909`](https://github.com/colesbury/nogil-3.12/commit/31ec6f02909) pystate: refcount threads to handle race between interpreter shutdown and thread exit
- [ ] [`45bdd27ee59`](https://github.com/colesbury/nogil-3.12/commit/45bdd27ee59) threading: make _thread.lock thread-safe
- [ ] [`07f5f8c318d`](https://github.com/colesbury/nogil-3.12/commit/07f5f8c318d) slice: move slice_cache to per-thread state
- [ ] [`ea1160c6d76`](https://github.com/colesbury/nogil-3.12/commit/ea1160c6d76) asyncio: fix race conditions in enter_task and leave_task
- [ ] [`212fef480ec`](https://github.com/colesbury/nogil-3.12/commit/212fef480ec) object.c: fix race when accessing attributes and methods
- [ ] [`70856f126dd`](https://github.com/colesbury/nogil-3.12/commit/70856f126dd) asdl: use _PyOnceFlag in Python-ast.c
- [ ] [`360a79cb885`](https://github.com/colesbury/nogil-3.12/commit/360a79cb885) socketmodule.c: use relaxed atomics for global 'defaulttimeout'
- [ ] [`041a08e3394`](https://github.com/colesbury/nogil-3.12/commit/041a08e3394) functools: make lru_cache thread-safe
- [ ] [`9bf62ffc4bd`](https://github.com/colesbury/nogil-3.12/commit/9bf62ffc4bd) random: add a mutex to guard random.Random
- [ ] [`a8251a8d255`](https://github.com/colesbury/nogil-3.12/commit/a8251a8d255) clinic: support '@' syntax for recursive mutexes
- [ ] [`ffade9d6f66`](https://github.com/colesbury/nogil-3.12/commit/ffade9d6f66) bufferedio: add locks to make print() thread-safe
- [ ] [`5b83c16dcd0`](https://github.com/colesbury/nogil-3.12/commit/5b83c16dcd0) textio: add locks to make textio thread-safe
- [ ] [`6323ca60f99`](https://github.com/colesbury/nogil-3.12/commit/6323ca60f99) stringio: make stringio thread-safe
- [ ] [`f1e4742eaa2`](https://github.com/colesbury/nogil-3.12/commit/f1e4742eaa2) deque: make most functions thread-safe
- [ ] [`78825e0508b`](https://github.com/colesbury/nogil-3.12/commit/78825e0508b) importlib: fix data race in imports (PyImport_ImportModuleLevelObject)
- [ ] [`2f5c90a2847`](https://github.com/colesbury/nogil-3.12/commit/2f5c90a2847) semaphore.c: decrease count before release sem_lock
- [ ] [`22eca6e2156`](https://github.com/colesbury/nogil-3.12/commit/22eca6e2156) sha1: make sha1module thread-safe
- [ ] [`ada9b73feba`](https://github.com/colesbury/nogil-3.12/commit/ada9b73feba) _struct: fix race condition in cache_struct_converter
- [ ] [`0e0b3899d15`](https://github.com/colesbury/nogil-3.12/commit/0e0b3899d15) signalmodule: fix thread-safety issue on macOS
- [ ] [`964bb33962a`](https://github.com/colesbury/nogil-3.12/commit/964bb33962a) json: make JSON scanner thread safe
- [ ] [`9ab96964e78`](https://github.com/colesbury/nogil-3.12/commit/9ab96964e78) faulthandler: don't dump all threads when running without the GIL
- [ ] [`cff32694a47`](https://github.com/colesbury/nogil-3.12/commit/cff32694a47) test_gdb: skip test_threads when running without GIL
- [ ] [`c9fc49666cc`](https://github.com/colesbury/nogil-3.12/commit/c9fc49666cc) test: add support for checking for TSAN
- [ ] [`7507a77a986`](https://github.com/colesbury/nogil-3.12/commit/7507a77a986) thread: don't use sem_clockwait with TSAN
- [ ] [`a62d37674cf`](https://github.com/colesbury/nogil-3.12/commit/a62d37674cf) _posixsubprocess: disable vfork when running with ASAN
- [ ] [`398204d57bf`](https://github.com/colesbury/nogil-3.12/commit/398204d57bf) object: fix reported TSAN races
- [ ] [`2ae5ee5ed48`](https://github.com/colesbury/nogil-3.12/commit/2ae5ee5ed48) tests: fix and work around some race conditions in tests
- [ ] [`9f9b3d085fd`](https://github.com/colesbury/nogil-3.12/commit/9f9b3d085fd) ceval: fix some thread-safety issues
- [ ] [`2a4c17e8964`](https://github.com/colesbury/nogil-3.12/commit/2a4c17e8964) pystate: move freelists to per-thread state
- [ ] [`9c1f7ba1b45`](https://github.com/colesbury/nogil-3.12/commit/9c1f7ba1b45) mro: thread-safe MRO cache
- [ ] [`149ea9dc439`](https://github.com/colesbury/nogil-3.12/commit/149ea9dc439) Deferred reference counting
- [ ] [`7e7568672d7`](https://github.com/colesbury/nogil-3.12/commit/7e7568672d7) specialize: make specialization thread-safe
- [ ] [`90d34f0d187`](https://github.com/colesbury/nogil-3.12/commit/90d34f0d187) specialize: optimize for single-threaded programs
- [ ] [`ff38d18f1e2`](https://github.com/colesbury/nogil-3.12/commit/ff38d18f1e2) odictobject: remove unused odictobject.c.h
- [ ] [`86e7772c648`](https://github.com/colesbury/nogil-3.12/commit/86e7772c648) http: fix dependency on finalization order
- [ ] [`60cd2e71b2c`](https://github.com/colesbury/nogil-3.12/commit/60cd2e71b2c) gc: separate GC heap for objects with pre-header
- [ ] [`b673db42609`](https://github.com/colesbury/nogil-3.12/commit/b673db42609) gc: remove use of PyGC_Head
- [ ] [`54a59bb2bcc`](https://github.com/colesbury/nogil-3.12/commit/54a59bb2bcc) clinic: remove _PyGC_Head_UNUSED
- [ ] [`17c1b147ff5`](https://github.com/colesbury/nogil-3.12/commit/17c1b147ff5) Add PyMutex to object.h
- [ ] [`065a269d67c`](https://github.com/colesbury/nogil-3.12/commit/065a269d67c) Use per-object mutex in more places
- [ ] [`cc13ec1470d`](https://github.com/colesbury/nogil-3.12/commit/cc13ec1470d) object: use Py_ssize_t for ob_ref_shared
- [ ] [`357a207f178`](https://github.com/colesbury/nogil-3.12/commit/357a207f178) dict/list: move shared flag to ob_gc_bits
- [ ] [`42d3e11d8ce`](https://github.com/colesbury/nogil-3.12/commit/42d3e11d8ce) code: make code object use deferred reference counting
- [ ] [`d5959118f81`](https://github.com/colesbury/nogil-3.12/commit/d5959118f81) objects: immortalize some objects
- [ ] [`4526c07caee`](https://github.com/colesbury/nogil-3.12/commit/4526c07caee) Disable the GIL by default
